import { describe, expect, it } from 'vitest';
import {
  applyChange,
  restoreBaseline,
  saveBaseline,
  type Cafe24Product,
  type LogEntry,
  type ProductState,
  type SyncDeps,
} from '@/lib/cafe24/product-sync';

// 가짜 카페24 몰: wildmental의 상품 16(P000000Q, 5,200원)을 메모리에 둔다.
function fakeMall(overrides: Partial<Cafe24Product> = {}) {
  const product: Cafe24Product = {
    product_no: 16,
    product_code: 'P000000Q',
    product_name: '향기로운 허브 쌀치아바타',
    price: '5200.00',
    summary_description: 'Sample Product Generated by CAFE24',
    ...overrides,
  };
  let state: ProductState | null = null;
  const logs: LogEntry[] = [];
  const puts: Record<string, unknown>[] = [];
  let failNextPut: Error | null = null;

  const deps: SyncDeps = {
    async getProduct() {
      return { ...product };
    },
    async getCategoryProductNos() {
      return [16, 17];
    },
    async putProduct(fields) {
      puts.push({ ...fields });
      if (failNextPut) {
        const e = failNextPut;
        failNextPut = null;
        throw e;
      }
      if (fields.price !== undefined) product.price = `${fields.price}.00`;
      if (fields.summary_description !== undefined) product.summary_description = fields.summary_description;
    },
    async loadState() {
      return state;
    },
    async saveState(next) {
      state = next;
    },
    async log(entry) {
      logs.push(entry);
    },
  };
  return {
    deps,
    product,
    logs,
    puts,
    state: () => state,
    failNextPut: (e: Error) => (failNextPut = e),
  };
}

describe('상품 16 연동 흐름', () => {
  it('기준값은 처음 한 번만 저장하고 덮어쓰지 않는다', async () => {
    const mall = fakeMall();
    const first = await saveBaseline(mall.deps);
    expect(first.created).toBe(true);
    expect(mall.state()?.baseline).toEqual({ price: 5200, summary_description: 'Sample Product Generated by CAFE24' });

    mall.product.price = '9999.00';
    const second = await saveBaseline(mall.deps);
    expect(second.created).toBe(false);
    expect(mall.state()?.baseline.price).toBe(5200);
  });

  it('상품코드가 P000000Q가 아니면 아무것도 저장하지 않는다', async () => {
    const mall = fakeMall({ product_code: 'P000000X' });
    await expect(saveBaseline(mall.deps)).rejects.toMatchObject({ code: 'PRODUCT_MISMATCH' });
    expect(mall.state()).toBeNull();
  });

  it('down + 할인 적용 → 4,940원, 바뀐 필드만 PUT, 재조회로 확인', async () => {
    const mall = fakeMall();
    await saveBaseline(mall.deps);
    const result = await applyChange(mall.deps, 'down', true);
    expect(result.result).toBe('applied');
    expect(result.after.price).toBe(4940);
    expect(Object.keys(mall.puts[0]).sort()).toEqual(['price', 'summary_description']);
    expect(mall.state()?.scenario).toBe('down');
  });

  it('같은 적용을 반복하면 PUT을 보내지 않는다(카페24 409 방지 · 누적 할인 없음)', async () => {
    const mall = fakeMall();
    await saveBaseline(mall.deps);
    await applyChange(mall.deps, 'down', true);
    const again = await applyChange(mall.deps, 'down', true);
    expect(again.result).toBe('already');
    expect(mall.puts).toHaveLength(1);
    expect(mall.product.price).toBe('4940.00');
  });

  it('PUT이 타임아웃이어도 재조회 값이 목표와 같으면 applied', async () => {
    const mall = fakeMall();
    await saveBaseline(mall.deps);
    const timeout = Object.assign(new Error('timeout'), { name: 'TimeoutError' });
    // 카페24에는 반영됐지만 응답만 늦게 온 상황을 흉내 낸다.
    mall.deps.putProduct = async (fields) => {
      mall.product.price = `${fields.price}.00`;
      mall.product.summary_description = fields.summary_description ?? mall.product.summary_description;
      throw timeout;
    };
    const result = await applyChange(mall.deps, 'down', true);
    expect(result.result).toBe('applied');
  });

  it('PUT이 거절되고 값이 그대로면 failed로 기록한다', async () => {
    const mall = fakeMall();
    await saveBaseline(mall.deps);
    mall.failNextPut(Object.assign(new Error('422'), { status: 422, code: 'invalid' }));
    await expect(applyChange(mall.deps, 'up', false)).rejects.toMatchObject({ code: 'WRITE_FAILED' });
    expect(mall.logs.at(-1)).toMatchObject({ result: 'failed', errorCode: 'HTTP_422:invalid' });
  });

  it('복원하면 5,200원과 원래 요약설명으로 돌아온다', async () => {
    const mall = fakeMall();
    await saveBaseline(mall.deps);
    await applyChange(mall.deps, 'down', true);
    const restored = await restoreBaseline(mall.deps);
    expect(restored.result).toBe('applied');
    expect(mall.product.price).toBe('5200.00');
    expect(mall.product.summary_description).toBe('Sample Product Generated by CAFE24');
    expect(mall.state()?.applied).toBeNull();
  });

  it('적용 후 관리자 화면에서 가격을 바꿨다면 복원을 멈춘다(409)', async () => {
    const mall = fakeMall();
    await saveBaseline(mall.deps);
    await applyChange(mall.deps, 'down', true);
    mall.product.price = '4500.00';
    await expect(restoreBaseline(mall.deps)).rejects.toMatchObject({ status: 409, code: 'EDITED_ELSEWHERE' });
    expect(mall.product.price).toBe('4500.00');
  });
});
